module.exports = {
  apps: [
    {
      name: 'redis',
      script: 'redis-server',
      args: '--port 6379 --bind 127.0.0.1 --protected-mode yes --dir /app/data/redis --appendonly yes --daemonize no',
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: 'metadata-service',
      script: 'dist/src/microservices/metadata-service/index.js',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        METADATA_SERVICE_PORT: 3005,
        PORT: 3005,
        DATABASE_URL: process.env.DATABASE_URL || 'file:/app/data/backup-meta.db',
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: 'backup-orchestrator',
      script: 'dist/src/microservices/backup-orchestrator/index.js',
      args: '--port 3001',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        ORCHESTRATOR_PORT: 3001,
        ORCHESTRATOR_URL: 'http://127.0.0.1:3001',
        METADATA_SERVICE_URL: 'http://127.0.0.1:3005',
        REDIS_HOST: '127.0.0.1',
        REDIS_PORT: 6379,
        POSTGRES_SERVICE_URL: 'http://127.0.0.1:3010',
        MYSQL_SERVICE_URL: 'http://127.0.0.1:3011',
        MONGODB_SERVICE_URL: 'http://127.0.0.1:3012',
        SQLITE_SERVICE_URL: 'http://127.0.0.1:3013',
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: 'postgres-backup',
      script: 'dist/src/microservices/database-services/postgres/service.js',
      args: '--port 3010',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        POSTGRES_SERVICE_PORT: 3010,
        SERVICE_PORT: 3010,
        BACKUP_PATH: process.env.BACKUP_PATH || '/app/backups',
      },
      autorestart: true,
      max_restarts: 10,
    },
    {
      name: 'mysql-backup',
      script: 'dist/src/microservices/database-services/mysql/service.js',
      args: '--port 3011',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        MYSQL_SERVICE_PORT: 3011,
        SERVICE_PORT: 3011,
        BACKUP_PATH: process.env.BACKUP_PATH || '/app/backups',
      },
      autorestart: true,
      max_restarts: 10,
    },
    {
      name: 'mongodb-backup',
      script: 'dist/src/microservices/database-services/mongodb/service.js',
      args: '--port 3012',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        MONGODB_SERVICE_PORT: 3012,
        SERVICE_PORT: 3012,
        BACKUP_PATH: process.env.BACKUP_PATH || '/app/backups',
      },
      autorestart: true,
      max_restarts: 10,
    },
    {
      name: 'sqlite-backup',
      script: 'dist/src/microservices/database-services/sqlite/service.js',
      args: '--port 3013',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        SQLITE_SERVICE_PORT: 3013,
        SERVICE_PORT: 3013,
        BACKUP_PATH: process.env.BACKUP_PATH || '/app/backups',
      },
      autorestart: true,
      max_restarts: 10,
    },
    {
      name: 'backup-workers',
      script: 'dist/src/index.js',
      args: '--worker',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        REDIS_HOST: '127.0.0.1',
        REDIS_PORT: 6379,
        METADATA_SERVICE_URL: 'http://127.0.0.1:3005',
        POSTGRES_SERVICE_URL: 'http://127.0.0.1:3010',
        MYSQL_SERVICE_URL: 'http://127.0.0.1:3011',
        MONGODB_SERVICE_URL: 'http://127.0.0.1:3012',
        SQLITE_SERVICE_URL: 'http://127.0.0.1:3013',
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: 'scheduler-service',
      script: 'dist/src/microservices/scheduler-service/index.js',
      args: '--port 3020',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        SCHEDULER_PORT: 3020,
        ORCHESTRATOR_URL: 'http://127.0.0.1:3001',
        METADATA_SERVICE_URL: 'http://127.0.0.1:3005',
        REDIS_HOST: '127.0.0.1',
        REDIS_PORT: 6379,
      },
      autorestart: true,
      max_restarts: 10,
    },
    {
      name: 'api-gateway',
      script: 'dist/src/server.js',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        GATEWAY_PORT: 3000,
        PORT: 3000,
        ORCHESTRATOR_URL: 'http://127.0.0.1:3001',
        METADATA_SERVICE_URL: 'http://127.0.0.1:3005',
        REDIS_HOST: '127.0.0.1',
        REDIS_PORT: 6379,
      },
      autorestart: true,
      max_restarts: 10,
    },
  ],
};
