FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY dist/src/microservices/gateway ./dist/src/microservices/gateway
COPY dist/src/logger ./dist/src/logger
COPY dist/src/config ./dist/src/config

EXPOSE 3000

CMD ["node", "dist/src/microservices/gateway/index.js"]